# Generated by Django 2.0.5 on 2018-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='img',
            field=models.ImageField(default='', upload_to='img2'),
            preserve_default=False,
        ),
    ]
