# Generated by Django 2.0.5 on 2018-06-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogspost_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgEncoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('face_recognition_encoding', models.TextField()),
            ],
        ),
    ]
